### ISSUE TITLE
Bug when using w/Transcoder

### ISSUE THREAD

**Issue by kboek** [WowzaMediaSystems/wse-plugin-blackliststreams#1]
See ServerListenerBlacklistStreams.java line 157. Transcoded streams have no Client object, and this code assumes that (client == null) means it's an RTP stream. 

First of all, it's best to check if stream.isTranscodeResult() at the start of the method. Secondly, it's not good practice to assume it's RTP when stream.getClient() is null. 

```
public void onPublish(IMediaStream stream, String streamName, boolean isRecord, boolean isAppend) 
{
  if (!stream.isTranscodeResult()) return;
  
  if (stream.getClient() != null) 
  {
    // ...
  }
  else if (stream.getRTPStream() != null)
  {
    // ...
  }
}

**Comment by rogerlittin** [comment]
Hi Karel,

I'll pull this in and also make an extra change to detect if the stream being published is a mediaCaster stream. The module should only be checking streams that are initiated from a remote source so includes RTMP encoders and RTSP encoders. Everything else is initiated on the server side and can be controlled by other means.

-Roger.

**Comment by akeller** [comment]
Stale, closing.
